# These are supported funding model platforms

# แสดงปุ่ม GitHub Sponsors ของคุณ
github: [Pheem49]

# หากในอนาคตคุณสมัครบริการอื่นเพิ่ม สามารถนำมาใส่ต่อท้ายได้ เช่น:
# buy_me_a_coffee: Pheem49
# ko_fi: Pheem49
